/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TechnicalGuideRouteImport } from './routes/technical-guide'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as IndexRouteImport } from './routes/index'

const TechnicalGuideRoute = TechnicalGuideRouteImport.update({
  id: '/technical-guide',
  path: '/technical-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/schedule': typeof ScheduleRoute
  '/technical-guide': typeof TechnicalGuideRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/schedule': typeof ScheduleRoute
  '/technical-guide': typeof TechnicalGuideRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/schedule': typeof ScheduleRoute
  '/technical-guide': typeof TechnicalGuideRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/schedule' | '/technical-guide'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/schedule' | '/technical-guide'
  id: '__root__' | '/' | '/schedule' | '/technical-guide'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ScheduleRoute: typeof ScheduleRoute
  TechnicalGuideRoute: typeof TechnicalGuideRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/technical-guide': {
      id: '/technical-guide'
      path: '/technical-guide'
      fullPath: '/technical-guide'
      preLoaderRoute: typeof TechnicalGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ScheduleRoute: ScheduleRoute,
  TechnicalGuideRoute: TechnicalGuideRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
