/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TechnicalGuideRouteImport } from './routes/technical-guide'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as RoutesRouteImport } from './routes/routes'
import { Route as RidersRouteImport } from './routes/riders'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProgrammeRouteImport } from './routes/programme'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as MediaRouteImport } from './routes/media'
import { Route as LiveRouteImport } from './routes/live'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as FansRouteImport } from './routes/fans'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoutesIndexRouteImport } from './routes/routes.index'
import { Route as MediaIndexRouteImport } from './routes/media.index'
import { Route as RoutesSlugRouteImport } from './routes/routes.$slug'
import { Route as RidersWatchRouteImport } from './routes/riders.watch'
import { Route as MediaPressRouteImport } from './routes/media.press'
import { Route as MediaGalleryRouteImport } from './routes/media.gallery'
import { Route as MediaContactRouteImport } from './routes/media.contact'
import { Route as MediaPressIndexRouteImport } from './routes/media.press.index'
import { Route as MediaPressSlugRouteImport } from './routes/media.press.$slug'
import { Route as MediaNoticesRefNoRouteImport } from './routes/media.notices.$refNo'

const TechnicalGuideRoute = TechnicalGuideRouteImport.update({
  id: '/technical-guide',
  path: '/technical-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesRoute = RoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => rootRouteImport,
} as any)
const RidersRoute = RidersRouteImport.update({
  id: '/riders',
  path: '/riders',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammeRoute = ProgrammeRouteImport.update({
  id: '/programme',
  path: '/programme',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const FansRoute = FansRouteImport.update({
  id: '/fans',
  path: '/fans',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesIndexRoute = RoutesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RoutesRoute,
} as any)
const MediaIndexRoute = MediaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MediaRoute,
} as any)
const RoutesSlugRoute = RoutesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RoutesRoute,
} as any)
const RidersWatchRoute = RidersWatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => RidersRoute,
} as any)
const MediaPressRoute = MediaPressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => MediaRoute,
} as any)
const MediaGalleryRoute = MediaGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => MediaRoute,
} as any)
const MediaContactRoute = MediaContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => MediaRoute,
} as any)
const MediaPressIndexRoute = MediaPressIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MediaPressRoute,
} as any)
const MediaPressSlugRoute = MediaPressSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MediaPressRoute,
} as any)
const MediaNoticesRefNoRoute = MediaNoticesRefNoRouteImport.update({
  id: '/notices/$refNo',
  path: '/notices/$refNo',
  getParentRoute: () => MediaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fans': typeof FansRoute
  '/guide': typeof GuideRoute
  '/live': typeof LiveRoute
  '/media': typeof MediaRouteWithChildren
  '/partners': typeof PartnersRoute
  '/programme': typeof ProgrammeRoute
  '/register': typeof RegisterRoute
  '/results': typeof ResultsRoute
  '/riders': typeof RidersRouteWithChildren
  '/routes': typeof RoutesRouteWithChildren
  '/schedule': typeof ScheduleRoute
  '/technical-guide': typeof TechnicalGuideRoute
  '/media/contact': typeof MediaContactRoute
  '/media/gallery': typeof MediaGalleryRoute
  '/media/press': typeof MediaPressRouteWithChildren
  '/riders/watch': typeof RidersWatchRoute
  '/routes/$slug': typeof RoutesSlugRoute
  '/media/': typeof MediaIndexRoute
  '/routes/': typeof RoutesIndexRoute
  '/media/notices/$refNo': typeof MediaNoticesRefNoRoute
  '/media/press/$slug': typeof MediaPressSlugRoute
  '/media/press/': typeof MediaPressIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fans': typeof FansRoute
  '/guide': typeof GuideRoute
  '/live': typeof LiveRoute
  '/partners': typeof PartnersRoute
  '/programme': typeof ProgrammeRoute
  '/register': typeof RegisterRoute
  '/results': typeof ResultsRoute
  '/riders': typeof RidersRouteWithChildren
  '/schedule': typeof ScheduleRoute
  '/technical-guide': typeof TechnicalGuideRoute
  '/media/contact': typeof MediaContactRoute
  '/media/gallery': typeof MediaGalleryRoute
  '/riders/watch': typeof RidersWatchRoute
  '/routes/$slug': typeof RoutesSlugRoute
  '/media': typeof MediaIndexRoute
  '/routes': typeof RoutesIndexRoute
  '/media/notices/$refNo': typeof MediaNoticesRefNoRoute
  '/media/press/$slug': typeof MediaPressSlugRoute
  '/media/press': typeof MediaPressIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fans': typeof FansRoute
  '/guide': typeof GuideRoute
  '/live': typeof LiveRoute
  '/media': typeof MediaRouteWithChildren
  '/partners': typeof PartnersRoute
  '/programme': typeof ProgrammeRoute
  '/register': typeof RegisterRoute
  '/results': typeof ResultsRoute
  '/riders': typeof RidersRouteWithChildren
  '/routes': typeof RoutesRouteWithChildren
  '/schedule': typeof ScheduleRoute
  '/technical-guide': typeof TechnicalGuideRoute
  '/media/contact': typeof MediaContactRoute
  '/media/gallery': typeof MediaGalleryRoute
  '/media/press': typeof MediaPressRouteWithChildren
  '/riders/watch': typeof RidersWatchRoute
  '/routes/$slug': typeof RoutesSlugRoute
  '/media/': typeof MediaIndexRoute
  '/routes/': typeof RoutesIndexRoute
  '/media/notices/$refNo': typeof MediaNoticesRefNoRoute
  '/media/press/$slug': typeof MediaPressSlugRoute
  '/media/press/': typeof MediaPressIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fans'
    | '/guide'
    | '/live'
    | '/media'
    | '/partners'
    | '/programme'
    | '/register'
    | '/results'
    | '/riders'
    | '/routes'
    | '/schedule'
    | '/technical-guide'
    | '/media/contact'
    | '/media/gallery'
    | '/media/press'
    | '/riders/watch'
    | '/routes/$slug'
    | '/media/'
    | '/routes/'
    | '/media/notices/$refNo'
    | '/media/press/$slug'
    | '/media/press/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fans'
    | '/guide'
    | '/live'
    | '/partners'
    | '/programme'
    | '/register'
    | '/results'
    | '/riders'
    | '/schedule'
    | '/technical-guide'
    | '/media/contact'
    | '/media/gallery'
    | '/riders/watch'
    | '/routes/$slug'
    | '/media'
    | '/routes'
    | '/media/notices/$refNo'
    | '/media/press/$slug'
    | '/media/press'
  id:
    | '__root__'
    | '/'
    | '/fans'
    | '/guide'
    | '/live'
    | '/media'
    | '/partners'
    | '/programme'
    | '/register'
    | '/results'
    | '/riders'
    | '/routes'
    | '/schedule'
    | '/technical-guide'
    | '/media/contact'
    | '/media/gallery'
    | '/media/press'
    | '/riders/watch'
    | '/routes/$slug'
    | '/media/'
    | '/routes/'
    | '/media/notices/$refNo'
    | '/media/press/$slug'
    | '/media/press/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FansRoute: typeof FansRoute
  GuideRoute: typeof GuideRoute
  LiveRoute: typeof LiveRoute
  MediaRoute: typeof MediaRouteWithChildren
  PartnersRoute: typeof PartnersRoute
  ProgrammeRoute: typeof ProgrammeRoute
  RegisterRoute: typeof RegisterRoute
  ResultsRoute: typeof ResultsRoute
  RidersRoute: typeof RidersRouteWithChildren
  RoutesRoute: typeof RoutesRouteWithChildren
  ScheduleRoute: typeof ScheduleRoute
  TechnicalGuideRoute: typeof TechnicalGuideRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/technical-guide': {
      id: '/technical-guide'
      path: '/technical-guide'
      fullPath: '/technical-guide'
      preLoaderRoute: typeof TechnicalGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes': {
      id: '/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof RoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/riders': {
      id: '/riders'
      path: '/riders'
      fullPath: '/riders'
      preLoaderRoute: typeof RidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programme': {
      id: '/programme'
      path: '/programme'
      fullPath: '/programme'
      preLoaderRoute: typeof ProgrammeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fans': {
      id: '/fans'
      path: '/fans'
      fullPath: '/fans'
      preLoaderRoute: typeof FansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/': {
      id: '/routes/'
      path: '/'
      fullPath: '/routes/'
      preLoaderRoute: typeof RoutesIndexRouteImport
      parentRoute: typeof RoutesRoute
    }
    '/media/': {
      id: '/media/'
      path: '/'
      fullPath: '/media/'
      preLoaderRoute: typeof MediaIndexRouteImport
      parentRoute: typeof MediaRoute
    }
    '/routes/$slug': {
      id: '/routes/$slug'
      path: '/$slug'
      fullPath: '/routes/$slug'
      preLoaderRoute: typeof RoutesSlugRouteImport
      parentRoute: typeof RoutesRoute
    }
    '/riders/watch': {
      id: '/riders/watch'
      path: '/watch'
      fullPath: '/riders/watch'
      preLoaderRoute: typeof RidersWatchRouteImport
      parentRoute: typeof RidersRoute
    }
    '/media/press': {
      id: '/media/press'
      path: '/press'
      fullPath: '/media/press'
      preLoaderRoute: typeof MediaPressRouteImport
      parentRoute: typeof MediaRoute
    }
    '/media/gallery': {
      id: '/media/gallery'
      path: '/gallery'
      fullPath: '/media/gallery'
      preLoaderRoute: typeof MediaGalleryRouteImport
      parentRoute: typeof MediaRoute
    }
    '/media/contact': {
      id: '/media/contact'
      path: '/contact'
      fullPath: '/media/contact'
      preLoaderRoute: typeof MediaContactRouteImport
      parentRoute: typeof MediaRoute
    }
    '/media/press/': {
      id: '/media/press/'
      path: '/'
      fullPath: '/media/press/'
      preLoaderRoute: typeof MediaPressIndexRouteImport
      parentRoute: typeof MediaPressRoute
    }
    '/media/press/$slug': {
      id: '/media/press/$slug'
      path: '/$slug'
      fullPath: '/media/press/$slug'
      preLoaderRoute: typeof MediaPressSlugRouteImport
      parentRoute: typeof MediaPressRoute
    }
    '/media/notices/$refNo': {
      id: '/media/notices/$refNo'
      path: '/notices/$refNo'
      fullPath: '/media/notices/$refNo'
      preLoaderRoute: typeof MediaNoticesRefNoRouteImport
      parentRoute: typeof MediaRoute
    }
  }
}

interface MediaPressRouteChildren {
  MediaPressSlugRoute: typeof MediaPressSlugRoute
  MediaPressIndexRoute: typeof MediaPressIndexRoute
}

const MediaPressRouteChildren: MediaPressRouteChildren = {
  MediaPressSlugRoute: MediaPressSlugRoute,
  MediaPressIndexRoute: MediaPressIndexRoute,
}

const MediaPressRouteWithChildren = MediaPressRoute._addFileChildren(
  MediaPressRouteChildren,
)

interface MediaRouteChildren {
  MediaContactRoute: typeof MediaContactRoute
  MediaGalleryRoute: typeof MediaGalleryRoute
  MediaPressRoute: typeof MediaPressRouteWithChildren
  MediaIndexRoute: typeof MediaIndexRoute
  MediaNoticesRefNoRoute: typeof MediaNoticesRefNoRoute
}

const MediaRouteChildren: MediaRouteChildren = {
  MediaContactRoute: MediaContactRoute,
  MediaGalleryRoute: MediaGalleryRoute,
  MediaPressRoute: MediaPressRouteWithChildren,
  MediaIndexRoute: MediaIndexRoute,
  MediaNoticesRefNoRoute: MediaNoticesRefNoRoute,
}

const MediaRouteWithChildren = MediaRoute._addFileChildren(MediaRouteChildren)

interface RidersRouteChildren {
  RidersWatchRoute: typeof RidersWatchRoute
}

const RidersRouteChildren: RidersRouteChildren = {
  RidersWatchRoute: RidersWatchRoute,
}

const RidersRouteWithChildren =
  RidersRoute._addFileChildren(RidersRouteChildren)

interface RoutesRouteChildren {
  RoutesSlugRoute: typeof RoutesSlugRoute
  RoutesIndexRoute: typeof RoutesIndexRoute
}

const RoutesRouteChildren: RoutesRouteChildren = {
  RoutesSlugRoute: RoutesSlugRoute,
  RoutesIndexRoute: RoutesIndexRoute,
}

const RoutesRouteWithChildren =
  RoutesRoute._addFileChildren(RoutesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FansRoute: FansRoute,
  GuideRoute: GuideRoute,
  LiveRoute: LiveRoute,
  MediaRoute: MediaRouteWithChildren,
  PartnersRoute: PartnersRoute,
  ProgrammeRoute: ProgrammeRoute,
  RegisterRoute: RegisterRoute,
  ResultsRoute: ResultsRoute,
  RidersRoute: RidersRouteWithChildren,
  RoutesRoute: RoutesRouteWithChildren,
  ScheduleRoute: ScheduleRoute,
  TechnicalGuideRoute: TechnicalGuideRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
